apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: v1
data:
  oauth2_proxy.cfg: >
    provider = "oidc"

    oidc_issuer_url = "https://youroktadomain.okta.com"

    upstreams = [
        "https://app.example.com",
        "https://app2.example.com"
    ]

    email_domains = [
        "*"
    ]

    client_id = "0xxxxx8"

    client_secret =
    "xxxxxxxOxxxx"

    pass_access_token = true

    cookie_secret = "cxxxxxx9"

    skip_provider_button = true
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: oauth2-proxy

# generate cookie token using python
# python -c 'import os,base64; print(base64.b64encode(os.urandom(16)))'